import json
import logging
import sys
import time
from datetime import datetime
from http.client import HTTPException
from pathlib import Path

from ambientweather2sqlite import mureq
from ambientweather2sqlite.awparser import extract_values
from ambientweather2sqlite.server import Server

from .database import insert_observation
from .metadata import create_metadata


class _JsonFormatter(logging.Formatter):
    """Format log records as single-line JSON (JSONL)."""

    def format(self, record: logging.LogRecord) -> str:
        entry: dict[str, object] = {
            "timestamp": self.formatTime(record),
            "level": record.levelname,
            "logger": record.name,
            "message": record.getMessage(),
        }
        if record.exc_info and record.exc_info[0] is not None:
            entry["exception"] = self.formatException(record.exc_info)
        return json.dumps(entry)


def _configure_logging(
    log_path: Path,
    *,
    log_format: str = "text",
) -> logging.Logger:
    """Set up file logging with the requested format."""
    logger = logging.getLogger("ambientweather2sqlite")
    logger.setLevel(logging.INFO)

    handler = logging.FileHandler(str(log_path))
    if log_format == "json":
        handler.setFormatter(_JsonFormatter())
    else:
        handler.setFormatter(
            logging.Formatter(
                "%(asctime)s - %(name)s - %(levelname)s - %(message)s",
            ),
        )
    logger.addHandler(handler)
    return logger


def clear_lines(n: int) -> None:
    for _ in range(n):
        print("\033[A\033[K", end="")


def wait_for_next_update(period_seconds: int) -> None:
    for i in range(period_seconds, 0, -1):
        print(f"\033[KNext update in {i} seconds", end="\r")
        time.sleep(1)


def fetch_once(live_data_url: str) -> None:
    """Fetch a single observation and print it without writing to the DB."""
    try:
        body = mureq.get(live_data_url)
        live_data = extract_values(body)
    except TimeoutError:
        print("Error: Weather station timed out.", file=sys.stderr)
        sys.exit(1)
    except HTTPException as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    print(json.dumps(live_data, indent=4))


def start_daemon(
    live_data_url: str,
    database_path: str,
    *,
    port: int | None = None,
    period_seconds: int = 60,
    log_format: str = "text",
) -> None:
    print(f"Observing {live_data_url}")
    print("Press Ctrl+C to stop")

    log_path = Path(database_path).parent / f"{Path(database_path).stem}_daemon.log"
    logger = _configure_logging(log_path, log_format=log_format)

    labels: dict[str, str] = {}
    try:
        labels, _ = create_metadata(database_path, live_data_url)
    except (HTTPException, TimeoutError) as e:
        logger.info("%s\n%s", type(e).__name__, e)
        print(f"Error fetching metadata: {e}")

    server = None

    if port is not None:
        host = "localhost"
        print(f"Starting JSON server on http://{host}:{port}")
        server = Server(live_data_url, database_path, port, host)
        server.start()

    remove_newlines = 0
    try:
        while True:
            clear_lines(remove_newlines)
            try:
                body = mureq.get(live_data_url)
                live_data = extract_values(body)
            except TimeoutError:
                logger.info("TimeoutError")
                print("Warming up weather station's server...")
                remove_newlines = 1
                continue
            except HTTPException as e:
                logger.info("%s\n%s", type(e).__name__, e)
                print(f"Error fetching live data: {e}")
                remove_newlines = 1
                wait_for_next_update(period_seconds)
                continue
            print(f"Updated at: {datetime.now()}")
            labeled_data = {
                labels.get(key, key): value for key, value in live_data.items()
            }
            pretty_data = json.dumps(labeled_data, indent=4)
            # + 2 for the "Updated at" line and the newline generated by print()
            remove_newlines = pretty_data.count("\n") + 2
            print(pretty_data)
            insert_observation(database_path, live_data)
            wait_for_next_update(period_seconds)
    except KeyboardInterrupt:
        print(f"\nStopping... results saved to {database_path}")
        if server is not None:
            server.shutdown()
        sys.exit(0)
